### ISSUE TITLE
No jitserver binary in Semeru images?

### ISSUE THREAD

**Issue by azolotko** [eclipse-openj9/openj9-utils#88]
I'm trying to find `jitserver` binary in the `ibm-semeru-runtimes:open-8u332-b09-jre` image, as referenced in [values.yaml](https://github.com/eclipse-openj9/openj9-utils/blob/master/helm-chart/openj9-jitserver-chart/values.yaml#L26-L27) and [deployment.yaml](https://github.com/eclipse-openj9/openj9-utils/blob/master/helm-chart/openj9-jitserver-chart/templates/deployment.yaml#L50), but there appears to be none: 

```
podman run --rm -it ibm-semeru-runtimes:open-8u332-b09-jre bash -c jitserver
bash: jitserver: command not found
```

Am I using a wrong image?

**Comment by pshipton** [comment]
@mpirvu @dchopra001 @AdamBrousseau fyi.
I do see `jitserver` in the raw Semeru JRE, assuming this is for xlinux or plinux.
If it's zlinux, this is a known problem which will be corrected in the next release.

**Comment by azolotko** [comment]
@pshipton Thank you @pshipton! Indeed, I'm running `aarch64`.

**Comment by pshipton** [comment]
Right, not a supported platform for jitserver.

**Comment by AdamBrousseau** [comment]
Glad this is sorted. A friendly reminder we have a [Semeru-Runtimes repo](https://github.com/ibmruntimes/Semeru-Runtimes/issues) for reporting issues with the Semeru releases.
